use_gazebo: true

command_in_type: "unitless"
scale:
  linear:  0.1
  rotational:  0.1
  joint: 0.1

publish_period: 0.034
low_latency_mode: false

command_out_type: trajectory_msgs/JointTrajectory

publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

is_primary_planning_scene_monitor: true

move_group_name: arm
planning_frame: base_link

ee_frame_name: crane_x7_gripper_base_link
robot_link_command_frame: base_link

incoming_command_timeout:  0.1
num_outgoing_halt_msgs_to_publish: 4

lower_singularity_threshold:  17.0
hard_stop_singularity_threshold: 30.0 
joint_limit_margin: 0.1
leaving_singularity_threshold_multiplier: 2.0

cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /joint_state
status_topic: ~/status 
command_out_topic: /crane_x7_arm_controller/joint_trajectory

check_collisions: true 
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.01
scene_collision_proximity_threshold: 0.02