<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="gazebo_d435" params="camera">

    <gazebo>
      <plugin filename="ignition-gazebo-sensors-system" name="ignition::gazebo::systems::Sensors">
        <render_engine>ogre2</render_engine>
      </plugin>
    </gazebo>
    
    <gazebo reference="${camera}_color_frame">
      <sensor name="sim_d435" type="rgbd_camera">
        <update_rate>10</update_rate>
        <always_on>true</always_on>
        <topic>${camera}</topic>
        <ignition_frame_id>${camera}_color_frame</ignition_frame_id>
        <camera name="realsense_d435">
          <xacro:property name="head_camera_width" value="640"/>
          <xacro:property name="head_camera_height" value="360"/>
          <xacro:property name="head_camera_hfov" value="${radians(69.4)}"/>
          <xacro:property name="head_camera_focal_length" value="${head_camera_width / (2 * tan(head_camera_hfov / 2))}"/>
          <horizontal_fov>${head_camera_hfov}</horizontal_fov>
          <image>
            <width>${head_camera_width}</width>
            <height>${head_camera_height}</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>10.0</far>
          </clip>
          <depth_camera>
            <clip>
              <near>0.1</near>
              <far>3.0</far>
            </clip>
          </depth_camera>
          <optical_frame_id>${camera}_color_optical_frame</optical_frame_id>
          <lens>
            <intrinsics>
              <fx>${head_camera_focal_length}</fx>
              <fy>${head_camera_focal_length}</fy>
              <cx>${(head_camera_width + 1) / 2}</cx>
              <cy>${(head_camera_height + 1) / 2}</cy>
              <s>1.0</s>
            </intrinsics>
            <projection>
              <p_fx>${head_camera_focal_length}</p_fx>
              <p_fy>${head_camera_focal_length}</p_fy>
              <p_cx>${(head_camera_width + 1) / 2}</p_cx>
              <p_cy>${(head_camera_height + 1) / 2}</p_cy>
              <tx>0</tx>
              <ty>0</ty>
            </projection>
          </lens>
        </camera>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>
