- gz_topic_name: "clock"
  gz_type_name: "gz.msgs.Clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  direction: GZ_TO_ROS

- gz_topic_name: "/camera/image"
  gz_type_name: "gz.msgs.Image"
  ros_topic_name: "/camera/color/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  direction: GZ_TO_ROS

- gz_topic_name: "/camera/depth_image"
  gz_type_name: "gz.msgs.Image"
  ros_topic_name: "/camera/aligned_depth_to_color/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  direction: GZ_TO_ROS

- gz_topic_name: "/camera/points"
  gz_type_name: "gz.msgs.PointCloudPacked"
  ros_topic_name: "/camera/depth/color/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  direction: GZ_TO_ROS

- gz_topic_name: "/camera/camera_info"
  gz_type_name: "gz.msgs.CameraInfo"
  ros_topic_name: "/camera/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  direction: GZ_TO_ROS

- gz_topic_name: "/camera/camera_info"
  gz_type_name: "gz.msgs.CameraInfo"
  ros_topic_name: "/camera/aligned_depth_to_color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  direction: GZ_TO_ROS
